### ISSUE TITLE
Thank 50 cents for supporting Anti-CPP projects

### ISSUE THREAD

**Issue by ckhung** [cirosantilli/china-dictatorship#101]
This article:  [如何看待这个对抗五毛的新方法？](https://pincong.rocks/question/6601 ) from 品䓤 suggests a way to deal with 50 cents: post on the 50 cent's home page on twitter , thanking them for supporting e.g. Falun Gong, Hong Kong independence, recognizing 64 Tian An Men, ... According to the article, the 50 cent won't be able to delete the post. (I only occasionally use twitter, and only for reading, so I don't know how it works) They will be horrified because of their expected CCP's omni-surveillance and then leave the harrassed alone. Here are a few fun links to see how it works (even on FB): https://www.plurk.com/p/ng0i52 , https://www.plurk.com/p/ng6sd6, and here are ready texts for people to copy paste: https://www.plurk.com/p/ng49b1 

Other less relevant comment / minor suggestions / trivia:
- [我眼中大陆目前的真实现状（可能比你们想的还糟糕）](https://chinadigitaltimes.net/chinese/2020/04/%e5%93%81%e8%91%b1-%e6%88%91%e7%9c%bc%e4%b8%ad%e5%a4%a7%e9%99%86%e7%9b%ae%e5%89%8d%e7%9a%84%e7%9c%9f%e5%ae%9e%e7%8e%b0%e7%8a%b6%ef%bc%88%e5%8f%af%e8%83%bd%e6%af%94%e4%bd%a0%e4%bb%ac%e6%83%b3/)
- You should mention "小粉紅" (little pink). This refers to people who don't get paid by CCP but rather voluntarily speak for CCP, most likely because they have been raised brain-washed.
- 品葱 seems like an interesting site. I suppose it is blocked by the GFW?
- 2.11. Is the Chinese government is evil? => extra "is"
- Thanks for linking to my post: [為什麼我不刪五毛的回應反而要刪你的回應? ](https://ckhung0.blogspot.com/2017/07/50-cents-party.html). Would be nice if you show the (Chinese) title text in the link like I do here.

**Comment by cirosantilli** [comment]
Hi Chao-Kuei,

Nice to meet you.

> This article: 如何看待这个对抗五毛的新方法？

Thanks, added original version from https://chinadigitaltimes.net/chinese/2019/08/【麻辣总局】新型敏感词武器：赵弹磁铁/ to wumao section.

The idea does sound fun, but I'm not convinced it is an efficient/scalable measure since the wumaos can just create more accounts, I would just use platforms like GitHub that allow me to one click block such user accounts.

> 我眼中大陆目前的真实现状（可能比你们想的还糟糕）

Was it removed from pincong? People really need to learn to use webarchive.

> You should mention "小粉紅" (little pink). This refers to people who don't get paid by CCP but rather voluntarily speak for CCP, most likely because they have been raised brain-washed.

Awesome, I love anti-CCP slang! Added.

> 品葱 seems like an interesting site. I suppose it is blocked by the GFW?

Yes, they appear not to censor stuff as mentioned at: https://github.com/cirosantilli/china-dictatorship/tree/7c7a696a3928f4d36c7d86cd500a4ddc514758fb#pincong

Normally we can easily check if it is blocked by GFW with: https://zh.greatfire.org/test?url=https%3A//pincong.rocks/question/6601 as mentioned at: https://github.com/cirosantilli/china-dictatorship/tree/a4ec62b1a10fc1e822e8de451b93f8ccb0440dfe#greatfire but for some reason that check fails for pincong in particular.

But still, adding content there is pointless since it can be blocked by GFW at any time, using GitHub like this and Terminus2049 is the way to go.

> 2.11. Is the Chinese government is evil? => extra "is"

> Thanks for linking to my post: 為什麼我不刪五毛的回應反而要刪你的回應? . Would be nice if you show the (Chinese) title text in the link like I do here.

Done.

**Comment by ckhung** [comment]
Oh yes, Ciro, I forgot to thank you on behalf of the (by now hopefully more than 70% or 80%) Taiwanese people who value freedom and democracy. But your avatar is really both funny and disgusting, haha! And good choice of the green color -- 臉都綠了 haha!

我眼中大陆目前的真实现状（可能比你们想的还糟糕）This link is from CDT not from pincong, and it indeed is archived in the wayback machine. OK maybe I don't understand your question here.

Thanks for the links. I consider myself maybe more knowledgeable about CCP than 90% of Taiwanese. But you are really way more knowledgeable than 99.9% of Taiwanese. I will take time to read the links.

Oh and another term while we are at it: 韭菜 (chives) refers to the majority of the Chinese people -- especially including / when addressing the little pinks -- under the CCP dictatorship.  Chives are mindless, grow fast, and are reaped often, signifying what the citizens really mean to CCP. OK you may need to ask other people to phrase this one better than I do here. But this illustration from RebelPepper should give you an idea: https://pbs.twimg.com/media/D6eLlGLWsAAX6rc?format=jpg&name=4096x4096   
![image](https://user-images.githubusercontent.com/3609806/80310591-259a2480-880e-11ea-8238-73d197cbb7cb.png)

**Comment by cirosantilli** [comment]
Ah, going mildly crazy, I googled the other article title and there was a pincong copy of it. Those websites copy each other a lot XD

I'll have a look into the chives. I love jiucai jiaozi!!!
