### ISSUE TITLE
现在连github也要成为你们宣传或者发泄的地方了吗

### ISSUE THREAD

**Issue by cfreebuf** [cirosantilli/china-dictatorship#107]
支持你有言论自由，但是你觉得在github，像小丑一样疯狂宣传你的政治观点，你觉得合适吗？你不觉得这种行为，只会适得其反吗？我相信大部分普通国内程序员看到这些，只会愤怒，并不会探究你说的正确与否。可能因为意识形态、生活环境的不同，你会觉得国内的人愚昧，但是难道你不也是在自我洗脑并且给别人洗脑吗？其实和你说这些没有任何意义，矛盾与冲突根本无法调和，只希望未来十年百年，时间告诉人们对错。

**Comment by cirosantilli** [comment]
Hi cfreebuf,

> 支持你有言论自由，但是你觉得在github，像小丑一样疯狂宣传你的政治观点，你觉得合适吗？你不觉得这种行为，只会适得其反吗？

It could backfire, I already acknowledged that at: https://github.com/cirosantilli/china-dictatorship/tree/457ad487805e40841381e8b5f49e75480facd482#embargo

> 可能因为意识形态、生活环境的不同，你会觉得国内的人愚昧，但是难道你不也是在自我洗脑并且给别人洗脑吗？

I have said time and time again in the FAQ that the Chinese people are not ignorant and that everyone including me is brainwashed, e.g.: at https://github.com/cirosantilli/china-dictatorship/tree/457ad487805e40841381e8b5f49e75480facd482#brainwashed-by-usa I don't know why people keep suggesting that I think that.

It is likely due to: https://github.com/cirosantilli/china-dictatorship/tree/457ad487805e40841381e8b5f49e75480facd482#evil-west and language barrier.
