### ISSUE TITLE
What you do will make github & stackoverflow be blocked in China, please stop!

### ISSUE THREAD

**Issue by qiulang** [cirosantilli/china-dictatorship#114]
I know you have strong opinions about China politics , BUT what you do here and in stackoverflow will just make them be blocked in China, which will then hurt innocent Chinese programmers in the end.

So I beg you stop!

Please!!!

Qiulang

**Comment by cirosantilli** [comment]
Hi qiulang,

- https://github.com/cirosantilli/china-dictatorship/tree/a92d0649cd59728c182de1d7f62e4e1bd4846d07#harm-programmers
- https://github.com/cirosantilli/china-dictatorship/tree/a92d0649cd59728c182de1d7f62e4e1bd4846d07#embargo

**Comment by qiulang** [comment]
That won't happen while Chinese programmers will be hurt (hugely!)
I will suggest you take tim cook's way https://www.nytimes.com/2018/06/18/technology/apple-tim-cook-china.html

> “Each country in the world decides their laws and their regulations. And so your choice is: Do you participate, or do you stand on the sideline and yell at how things should be?”

The bottom line is I hate to see github & stackoverflow be blocked in China and what you do is helping them doing that!

**Comment by raaaaay-c** [comment]
@qiulang He isn't the guy who banned Github and Stackoverflow, send your complaints to Xijinping via : https://ts.isc.org.cn/complain/info

**Comment by pandadolphin** [comment]
@qiulang I don't think @cirosantilli would really listen. He thought he was doing the right thing. I kinda appreciate his effort, because he could just stand by. That's why I would call him a western democracy radical, like the preacher before Opium War.
What Ciro doesn't understand is, China is different from western countries, from culture to history. Therefore western-style democracy political system may suit them very well, but that doesn't mean it will work for China.
China now is the second largest economy in the world by GDP, and the living standard of Chinese people has improved significantly in the past 30 years. Compared with India, the so-called largest western-style democratic country, I think the result is obvious. Why all the countries in the world should implement the same system as western countries?
@cirosantilli Today is 2020. Let's just say 10 years later, if Chinese people were having a better life than today (by talking with local Chinese from different province of China), would you please stop pointing you fingers even with good intentions from your perspective?

**Comment by cirosantilli** [comment]
@pandadolphin hi there, please don't at mention me on threads as per: https://github.com/cirosantilli/china-dictatorship/blob/master/CONTRIBUTING.md

Feel free to open a new issue and repeat your thoughts there if you would like a reply.

I also don't reply to China stuff on Twitter except by pointing people to this repo as per policy: https://github.com/cirosantilli/china-dictatorship/tree/13e6c7af0fcdf052b6f52c2a79324e0deb319cb9#reply-policy

All best.

**Comment by qiulang** [comment]
@pandadolphin He just doesn't listen at all and I don't appreciate what he does at all either.
