### ISSUE TITLE
There should a balanced description of historical and current events at China

### ISSUE THREAD

**Issue by justicezyx** [cirosantilli/china-dictatorship#151]
Otherwise, this will be easily labeled "western propaganda" and got ignored by Chinese people.

For example, despite the concerted efforts by democratic-minded people inside China, all they have been doing inside China is to depict a picture of west that is "perfect". These images are easily debunked with a few reports on US gun violence and racism oppression, which can be freely extracted from US' own main stream media.

On the contrary, a balanced view would be more compelling to show a realistic picture, instead of a purely-evil one that will easily be rebuffed by Chinese people.

PS:
Assuming this repo intends to educate Chinese people, instead of pleasing western people.
I mean, I think everyone in west knows they are superior to Chinese, right?

**Comment by cirosantilli** [comment]
Hi Yaxiong,

> Otherwise, this will be easily labeled "western propaganda" and got ignored by Chinese people.

> For example, despite the concerted efforts by democratic-minded people inside China, all they have been doing inside China is to depict a picture of west that is "perfect". These images are easily debunked with a few reports on US gun violence and racism oppression, which can be freely extracted from US' own main stream media.

> On the contrary, a balanced view would be more compelling to show a realistic picture, instead of a purely-evil one that will easily be rebuffed by Chinese people.

> PS:
Assuming this repo intends to educate Chinese people, instead of pleasing western people.
I mean, I think everyone in west knows they are superior to Chinese, right?

If you feel there is a negative aspect of the West, which is better in China or other dictatorships, and has not been enough emphasized, please open specific issues one per topic explaining why.

It is however very important that the issue in question must be better in China/other dictatorships. Otherwise, we would start discussing hundreds of things which have nothing to do with China/dictatorships, and it would be too distracting for me to moderate.

Also, since there is freedom of speech in the West, these issues have already been infinitely debated elsewhere in places with many more people involved (and they haven't reached conclusions either).

Furthermore, the CCP is already doing a great job of pointing out all the things which are bad in the West, you just have to open the foreign section of any CCP media, and its an endless stream of that.

Or if you have specific examples of Chinese pro-democracy people who have proposed clearly false promises of a perfect society, that is also of interest, debunking such idiots is good.

Finally, consider that the primary goal of this repository is not to convince people. People's opinions are unchangeable. The primary goal of this repository is [https://github.com/cirosantilli/china-dictatorship/tree/a1b5b3dc644fe7c212ed7ad4a7a13509cb0d4f64#why-keyword-attack](the keyword attack). And the secondary goal are to have fun by teaching and learning fun stuff.

For example, if people had guns in Tiananmen, the CCP would have fallen. That's the rationale of the second amendement, and the downside are regular smaller shootings. There is infinite discussion elsewhere about this, the ups and downs are obvious, pointless to talk more.

About racism, I feel that the Chinese are at least as racist. It's just that there aren't huge amounts of poor black people in China. This is a worthwhile discussion, and if you have arguments why things are better in dictatorships, give them, but a conclusion will never be reached either way.

Related:

- https://cirosantilli.com/china-dictatorship/#western-democracies-are-not-perfect
- https://cirosantilli.com/china-dictatorship#evil-west
- https://cirosantilli.com/china-dictatorship/#bias

**Comment by justicezyx** [comment]
Nvm, I am talking about making this more appealing to Chinese people, who are heavily indoctrinated by CCP propaganda...

Up to you, this is your repo and your project. If you believe this is the best way despite my suggestion, then I have nothing more to offer.
