### ISSUE TITLE
[Deleted]

### ISSUE THREAD

**Issue by hykilpikonna** [cirosantilli/china-dictatorship#73]

**Comment by cirosantilli** [comment]
Hi Hykilpkonna,

> Sure dictatorship is bad from an American or European perspective, but it is economically more productive, and its citizens are relatively happy in their daily lives despite that they might not know anything negative about China's history. What good does it serve to have freedom but not really happy? What is the point of having an election if about half of all the people are going to be angry for four years that their political party isn't elected? I think it is better to live in blissful ignorance than to know the disturbing truths.

Yes, if dictatorships are better, we should have them, I'm just arguing they're not, e.g.: https://github.com/cirosantilli/china-dictatorship/tree/eb6df62c004569ddc16eabf4a3890443bc3dcebe#richer

> For minorities like Falun Gong members, or even members of any religion, they are minorities anyways. Even with open elections, religious freedom wouldn't win against the majority of citizens who deeply believe in atheism, who would scorn religion as superstition the second they hear it. So it might just be better for minorities to settle outside of China than to create acceptance for them in it.

It tends to be harder to crush minorities in democracies.

Intolerance is a risky way to live, what if you start doing something which is considered illegal on day?

Related: https://github.com/cirosantilli/china-dictatorship/tree/eb6df62c004569ddc16eabf4a3890443bc3dcebe#this-is-your-personal-problem-we-have-nothing-to-do-with-it-stop-punishing-us-for-it

> Also, from a practicality perspective, the average education level in China isn't ready to have a truly open election. From my observation, most Chinese citizens don't care about political beliefs.

Related: https://github.com/cirosantilli/china-dictatorship/tree/eb6df62c004569ddc16eabf4a3890443bc3dcebe#the-chinese-masses-are-still-uneducated-and-not-fit-for-free-speech-and-democracy

> Both political systems have their pros and cons, but dictatorship suites the Chinese environment and citizens the best. Please don't be so radical about this. China is certainly not going to start WW3 as you anticipated to prevent, because every country in the world knows that there are no benefits compared to drawbacks in starting a world-wide war. Why are you being so radical when residents in China are relatively happy, they have no problems with Chinese dictatorship, and you are not in China nor have a Chinese culture background?

Because I think you would be happier with democracy. Why don't you take a vote?
